### ISSUE TITLE
implement `types.MappingProxyType` instead of `DotMap`

### ISSUE THREAD

**Issue by 0hsn** [chkware/cli#103]
`chk/modules/http/request_helper.py` module have extensive dependency on [DotMap](https://pypi.org/project/dotmap/). We want to remove support for DotMap, and want to use [types.MappingProxyType](https://docs.python.org/3/library/types.html#types.MappingProxyType) or better data structure instead.

**Comment by sudiptob2** [comment]
As I have read about **DotMap**, I learned that it is used to access dictionaries using dot notation.
But in the `request_helper` file, you have not used any dot notation, instead used `request_data.get('key')` which is natively supported in `Dict`. There is one line though(112), which uses `body.toDict()` to convert **DotMap** to dictionary. 

**MappingProxyType** on the other hand will make the dictionary _read-only_. But It doesn't support accessing elements using dot notation. 
So why should we use **MappingProxyType** after removing the **DotMap**. Why can't we just use `dict[str, object] `as the type of `request_data`. 
Are there any special reasons for using **MappingProxyType?**

_I am aware of the fact that MappingProxyType provides a dynamic view on the mapping’s entries, which means that when the mapping changes, the view reflects these changes._

**Comment by sudiptob2** [comment]
Thanks for the explanation, I will work on this task
