### ISSUE TITLE
Refactor: HTTP module class finding and loading process

### ISSUE THREAD

**Issue by 0hsn** [chkware/cli#110]
in `chk/modules/http/main.py:execute` after making file context we are locating the class to load via finding the version and matching against `VersionStrToSpecConfigMapping`. This is dynamically loading the execution units. I want to get rid of this whole process.

The process in my mind:
- remove `chk.modules.version.support.SpecificationLoader` as a whole
- remove `chk.modules.version.constants.VersionStrToSpecConfigMapping:find_by_version`
- have two seperate dict (one for http another for testcase version list) on `chk.modules.version.constants.VersionStrToSpecConfigMapping`
- use the above dict for validation to see if the given version exists 
- then directly load `chk.modules.http.entities.HttpSpec` class

** also we need consume impact of updating `VersionStrToSpecConfigMapping` and some other, see if all test case passes

**Comment by 0hsn** [comment]
> > * have two seperate dict (one for http another for **_testcase_** version list) on
> 
> did you mean test-spec ?

yes, going forward we'll be calling them `testcase`. I already have updated the name on my branch (to be merged). therefore continue with name `test_spec` for base branch for now. Thanks.

**Comment by sudiptob2** [comment]
As per the refactoring goal, in `chk.modules.version.constants.VersionStrToSpecConfigMapping` I will remove `find_by_version` and plan to implement something like `validate_version` which will check if the given version is supported or not.
```
def validate_http_version(cls, key: str) :
    -------- some other validation -----
    if key not in http_version_list:
        raise SystemExit(err_message('fatal.V0004'))
```
What do you think @0hsn
