### ISSUE TITLE
Fromatted output should be able to supress with `--result`

### ISSUE THREAD

**Issue by 0hsn** [chkware/cli#113]
**What**

Response should always be formatted like #114. Formatted output should able to be suppressed by user from command-line like:

```bash
$ chk http --result [FILE]
```

blocked by: #114

**Comment by sudiptob2** [comment]
as of the current implementation, user can specify the return type in the `.chk` file. 
I think the logic is implemented in `chk.modules.http.support.request_get_return`. Is it possible to reuse this util to implement feature #113

**Comment by sudiptob2** [comment]
we have the document object in `http.execute` method. Depending on the `--result` swithch we can push the return type in the document object (of course with proper validation and all). 
In this way, I think we can achieve the desired result and utilize `chk.modules.http.support.request_get_return` at the same time.

For example
```python
    document['request']['return'] = '.code'
    file_ctx = FileContext(file, fpath_mangled, fpath_hash, document)
    http_spec = HttpSpec(file_ctx)
```

**Comment by 0hsn** [comment]
@sudiptob2 this ticket is about not showing [formatted output](https://github.com/chkware/cli/issues/114#issue-1311501439) and only show `[RESULT]` or `[EXCEPTION]` in case we have `--result`. Therefore, we are not expecting any value with `--result` flag this time, for now it's just a boolean flag.

I think the second part you discussed is related to #20 let's take the discussion there as related.

Kindly clarify if I misunderstood something 🙏

**Comment by sudiptob2** [comment]
can please you give an example output of --result flag

**Comment by 0hsn** [comment]
@sudiptob2 Expected response

```
$ chk http --result tests/resources/storage/sample_config/pass_cases/UserCreate/02_UserCreateSpecWithRequest.chk
[RESULT]
```
or 
```
$ chk http --result tests/resources/storage/sample_config/pass_cases/UserCreate/02_UserCreateSpecWithRequest.chk
[ERROR]
```

**Comment by sudiptob2** [comment]
That means, when the `--result` flag is provided we will not show `displayable_summary` ( the formatted header) right?

**Comment by 0hsn** [comment]
The reason being: to give user programmatic access to data so you can write following. The below example supposed to give you am email value in data object, if you understand what I mean.

```
$ chk http --result some_dir/some_file.chk | jq '.data.email'
```

**Comment by sudiptob2** [comment]
According to this issue, it seems that `--result` is a boolean flag. But in #20 we can see that result will also take different values.
So I am planning to use [choice option](https://click.palletsprojects.com/en/8.1.x/options/#choice-options) for implementing the `--result` flag. 
What do you think? @0hsn

**Comment by 0hsn** [comment]
@sudiptob2 let's plan for #20 when we schedule it for development. It depends on some other things not available on the software now, and I need to plan this part of the product behavior. So, let's skip the thought for now!
