### ISSUE TITLE
More Assert* function needed in AssertionCase

### ISSUE THREAD

**Issue by 0hsn** [chkware/cli#116]
[List of assertion to be supported](https://github.com/chkware/HEAD/blob/5bbdb30ad98207bf6d5d0ce4d0dc76244576814d/plan_docs/api-test-assertions.md)

- [x] assertIsMap
- [x] assertIsList
- [x] assertIsBool
- [x] assertIsFloat
- [x] assertIsInt
- [x] assertIsString
- [x] assertEmpty : object
- [x] assertEquals : object
- [x] assertNotEquals : object
- [x] assertFalse : bool
- [x] assertTrue
- [x] assertListContains:list
- [x] assertMapContains: dict
- [x] assertStrContains: str
- [x] assertMapHasKey: dict
- [x] assertMapDoNotHasKey: dict
- [x] assertMapHasKeys: dict
- [x] assertMapDoNotHasKeys: dict
- [x] assertMapExactKeys: dict
- [x] assertMapKeyCount: dict
- [x] assertListHasIndex: list
- [x] assertCount: list
- [x] assertGreaterThan: int, float
- [x] assertGreaterThanOrEqual: int, float
- [x] assertLessThan: : int, float
- [x] assertLessThanOrEqual: : int, float

**Comment by sudiptob2** [comment]
I am looking at the test case `assertListContains:list`. Does it mean we have to assert that  the `actual` contains `expected` 
For example, 
**Input**
``
expected = [1,2,3]
actual = 3
``
**Output**
`True`
