### ISSUE TITLE
build `zipapp`

### ISSUE THREAD

**Issue by 0hsn** [chkware/cli#132]
**What**

build a `zipapp` package that 
- requires no extra downloading on dependent packages
- user just download the zipapp and use as `python3 chk.pyz` (for 1st version of this zip app build)

**Expected outcome**
- documentation of how to create one containing list of steps

**Comment by sudiptob2** [comment]
As `chkware/cli` has third-party dependency I am planning to create the `zipapp` using [shiv](https://github.com/linkedin/shiv).

However, I doubt that packaging `chkware/cli` as `zipapp` will be fruitful. Because the user must have the exact same python version (which was used to package the zipapp)  to be able to run the  `zipapp`
@0hsn

**Comment by 0hsn** [comment]
Okay, so let's look into all the possibilities, problems, merits. Let's discuss before implement. @sudiptob2

**Comment by 0hsn** [comment]
@sudiptob2 Please list all of the findings you have, here in a comment for future reference

**Comment by sudiptob2** [comment]
I thought with zipapp we might be able to distribute chkware as a standalone application.
But to run the zipapp user must have the required python interpreter. 
Actually I mean to say, if we have python 3.10 dependencies, the user must have the python 3.10 installed beforehand.

Pip also provides the same solution, can you point out the extra benefits of zipapp over pip.

**Comment by 0hsn** [comment]
>  Actually I mean to say, if we have python 3.10 dependencies, the user must have the python 3.10 installed beforehand.

Yes they still need python to be installed. However, 
  - they won't need to install pipx, or upgrade pip before install
  - because all deps will be included in the zipapp - this will also help to remove package version deps
  - also, reduce network and maintenance cost on CI pipeline

TBH, I'd like to deliver an AOT compiled single executable, better

**Comment by sudiptob2** [comment]
Ok I will produce a document on creating `chk.pyz` using `shiv`

**Comment by 0hsn** [comment]
@sudiptob2 can you also look into it `pantsbuild/pex`

**Comment by sudiptob2** [comment]
sure

**Comment by 0hsn** [comment]
Documentation can be found here https://github.com/chkware/cli/blob/main/docs/build-zipapp.md
