### ISSUE TITLE
Find suitable hosting option for documentation, article, tutorial

### ISSUE THREAD

**Issue by 0hsn** [chkware/cli#16]
- [ ] Need domain name. Need suggestion.
- [x] #25 
- [x] CI/CD for continuous documentation deploy

**Comment by arifszn** [comment]
Doc hosting won't be on the Github page? I would vote for hosting the docs on Github page and later add a custom domain if needed.

And I will be taking over the ticket `CI/CD for continuous documentation deploy` if anyone has already started yet.

**Comment by 0hsn** [comment]
Hosting options:

- AWS S3 + Cloudfront (customizable, edge delivery, uncontrollable bill~)
- Vercel or similar (looks free, but I am sure its bait)
- Github pages (free, limited outbound bandwidth)
- Shared hosting (cheap, unreliable, CI/CD not possible~)
- [tbd]

**Comment by 0hsn** [comment]
> Need domain name. Need suggestion.

Will think about it after stable release
