### ISSUE TITLE
command line option to control display output for resquest response

### ISSUE THREAD

**Issue by 0hsn** [chkware/cli#20]
**What**

User should be able to select specific result by type from command line. 

```
# select response code to be displayed directly
--result=.code

# select response headers to be displayed directly
--result=.headers
```

blocked by #113

**Comment by sudiptob2** [comment]
I am planning to implement this feature inside `presentation.make_displayable`.  Something like the following, what do you think @0hsn 
```python3
def make_displayable(response: dict[str, object], ret:str):
    if ret not in ('version', 'code', 'reason', 'headers', 'body'):
        raise ValueError('Unsupported key in request.return')
    return #according to the ret
```
Also, we can move the supported return type to a central place.

**Comment by 0hsn** [comment]
this was handled in combination of `expose:` and `--result` command line opt
